/** Public API of the lead conversion auditor. */
export {
  groupMessagesIntoConversations,
  filterLeadConversations,
  type AuditMessage,
  type Conversation,
} from './conversations.js';

export {
  firstResponseTime,
  responseTimeBuckets,
  zeroReplyRate,
  afterHoursLeadShare,
  isWithinBusinessHours,
  responseDelayDropoff,
  staffHoursConsumed,
  backAndForthRounds,
  responseTimeVariance,
  dayHourHeatmap,
  repeatQuestionFrequency,
  meanReplyTime,
  revenueAtRisk,
  afterHoursRevenueAtRisk,
  nextBusinessOpenTimestamp,
  nextMorningReplyRate,
  afterHoursTimeBuckets,
  instantReplyRecoverable,
  computeAllAuditMetrics,
  buildTemplateTextSet,
  resolveOptions,
  percentile,
  DEFAULT_OPTIONS,
  BOOKING_INTENT_REGEX,
  QUESTION_PATTERNS,
  type AuditReport,
  type MetricOptions,
  type ResolvedMetricOptions,
  type BusinessHours,
  type ResponseTimeBuckets,
  type ZeroReplyRate,
  type AfterHoursLeadShare,
  type ResponseDelayDropoff,
  type StaffHoursConsumed,
  type BackAndForthRounds,
  type ResponseTimeVariance,
  type HeatmapCell,
  type RepeatQuestionFrequency,
  type MeanReplyTime,
  type RevenueAtRisk,
  type AfterHoursRevenueAtRisk,
  type NextMorningReplyRate,
  type AfterHoursTimeBuckets,
  type AfterHoursBucket,
  type InstantReplyRecoverable,
  type ConversationSummary,
} from './metrics.js';
